name: CI
on:
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
        with:
          python-version: 3.10
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check codestyle
        run: pycodestyle ./demopages/*.py
      - name: Tests
        run: python3 manage.py  test