name: CI
on:
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
        with:
          python-version: 3.10
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check codestyle
        run: pycodestyle ./demopages/*.py
      - name: Tests
        run: python3 manage.py  test
  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN}}
      NAME:  ${{ secrets.DOCKER_NAME}}
    steps:
      - name: Login to docker
        run: echo ${{secrets.DOCKER_TOKEN }} | docker login -u ${{secrets.DOCKER_LOGIN}} --password-stdin
      - uses: actions/checkout@main
      - name: Build  image
        run: docker build -t &LOGIN/&NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker
        run: docker push &LOGIN/&NAME:${GITHUB_REF:11}
